# Makefile for an A2F-Linux project

# This project's name
SAMPLE		:= i2c_test

# Custom applcations subdirectories that this project
# needs to build. Edit this list as appropriate for your application.
CUSTOM_APPS	:= app i2c-tools-3.1.0

# Include Make rules applicable to all projects
include ../Rules.make

