#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts none /dev/pts
# To do NFS-mount of a development host directory for your project,
# replace the IP and host directory in the line below with your
# values matching your local settings

#mount kernel debugfs
mount -t debugfs none /sys/kernel/debug/

ifconfig lo 127.0.0.1

echo "Mounting NAND drive"
mkdir /nand
mount -t jffs2 /dev/mtdblock2 /nand

echo "Mounting SD Card"
mkdir sdcard
mount /dev/mmcblk0p1 /sdcard

exec /nand/startup.sh

