# Makefile

SAMPLE		:= performand
CUSTOM_APPS	:= i2c-tools-3.1.0 driver/imu apps/daemons apps/wifi apps/mpu9150-cal apps/ble_simplemessenger_2

include ../Rules.make

# Clear temp files:
# find . -type f -name '*~' -delete

# end of file
